// <auto-generated />
namespace ECommerceSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class change_price_nullability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_price_nullability));
        
        string IMigrationMetadata.Id
        {
            get { return "202609040719361_change_price_nullability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
