// <auto-generated />
namespace ECommerceSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class add_categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_categories));
        
        string IMigrationMetadata.Id
        {
            get { return "202609031239185_add_categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
