// <auto-generated />
namespace ECommerceSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class create_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202609041242021_create_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
